# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83c8cd3eeae1903a42a60cfc5d15159e010e6409a2cb47bfcdb7654a9e77df3fe608bccf40e30e6fdc80185b9d2788def8e35646a5483a40d5ef69573f666349

test:
  secret_key_base: 652cd7bd4cc7958260da211f3030a047b139cc5f36d6460f515913bd998284c775057c93f54baec2139c09f3090d1cf60b799d3684a11207659cad5d9f6a56ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
